// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chat-first-response/Current.tsx": () => import("../components/mockups/chat-first-response/Current.tsx"),
  "./components/mockups/chat-first-response/InstantReply.tsx": () => import("../components/mockups/chat-first-response/InstantReply.tsx"),
  "./components/mockups/thanarah-workspace/Current.tsx": () => import("../components/mockups/thanarah-workspace/Current.tsx"),
  "./components/mockups/thanarah-workspace/Reference.tsx": () => import("../components/mockups/thanarah-workspace/Reference.tsx")
};
